### ISSUE TITLE
error

### ISSUE THREAD

**Issue by saurabhomer258** [delaroy/PaginationInfiniteScroll#1]
FATAL EXCEPTION: main
                                                                                           Process: com.delaroystudios.paginationinfinitescroll, PID: 9795
                                                                                           java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.delaroystudios.paginationinfinitescroll.model.MoviesResponse.getResults()' on a null object reference
                                                                                               at com.delaroystudios.paginationinfinitescroll.MainActivity.fetchResults(MainActivity.java:136)
                                                                                               at com.delaroystudios.paginationinfinitescroll.MainActivity.access$500(MainActivity.java:26)
                                                                                               at com.delaroystudios.paginationinfinitescroll.MainActivity$2.onResponse(MainActivity.java:113)
                                                                                               at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                               at android.os.Looper.loop(Looper.java:135)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:5382)
                                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:928)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:723)
04-22 23:40:46.131 9795-9795/com.delaroystudios.paginationinfinitescroll I/Process: Sending signal. PID: 9795 SIG: 9

**Comment by nizamudeenms** [comment]
Hi is this error resolved.

**Comment by Seddiks** [comment]
Same error..

**Comment by AKMohite** [comment]
![pagination_error](https://user-images.githubusercontent.com/18052898/44626149-694fd300-a935-11e8-9dc6-0cf36ff54310.png)

as you can see in response the body is null and response code is 401 so the list is not being passed
It is due to the api_key viz. not passed
